#!/bin/bash
###############################################################################
# 04-ssh-harden.sh - SSH Hardening Script
# Target: Ubuntu 24 E-Commerce Server
# Purpose: Secure SSH configuration while maintaining access
###############################################################################

set -euo pipefail

LOGFILE="/root/ccdc-logs/ssh_harden_$(date +%Y%m%d_%H%M%S).log"
BACKUP_DIR="/root/ccdc-backups/ssh_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$(dirname "$LOGFILE")" "$BACKUP_DIR"

log() {
    echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOGFILE"
}

log "Starting SSH hardening..."

# Backup current config
log "Backing up current SSH configuration..."
cp -a /etc/ssh "$BACKUP_DIR/"
cp -a /root/.ssh "$BACKUP_DIR/root_ssh" 2>/dev/null || true

log "Current SSH configuration:"
grep -E '^(Port|PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|MaxAuthTries|X11Forwarding)' /etc/ssh/sshd_config 2>/dev/null || true

echo ""
echo "============================================"
echo "SSH HARDENING OPTIONS"
echo "============================================"
echo "This script will apply security settings."
echo "IMPORTANT: Keep your current session open to test!"
echo ""

# Create hardened config
SSHD_CONFIG="/etc/ssh/sshd_config"

# Check if there's a config.d directory being used
if grep -q "^Include /etc/ssh/sshd_config.d" "$SSHD_CONFIG" 2>/dev/null; then
    log "Using sshd_config.d for custom settings..."
    CUSTOM_CONFIG="/etc/ssh/sshd_config.d/99-ccdc-hardening.conf"
else
    CUSTOM_CONFIG="$SSHD_CONFIG"
fi

read -p "Apply SSH hardening? (y/N): " -r REPLY
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log "Aborted by user"
    exit 0
fi

if [ "$CUSTOM_CONFIG" != "$SSHD_CONFIG" ]; then
    # Create a separate config file
    log "Creating hardening config at $CUSTOM_CONFIG"
    cat > "$CUSTOM_CONFIG" << 'EOF'
# CCDC SSH Hardening Configuration
# Generated by 04-ssh-harden.sh

# Disable root login with password (key-only if needed)
PermitRootLogin prohibit-password

# Enable password authentication (needed for competition)
PasswordAuthentication yes

# Enable public key authentication
PubkeyAuthentication yes

# Limit authentication attempts
MaxAuthTries 3

# Disable X11 forwarding
X11Forwarding no

# Disable TCP forwarding
AllowTcpForwarding no

# Disable agent forwarding
AllowAgentForwarding no

# Set login grace time
LoginGraceTime 30

# Use strong ciphers only
Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

# Use strong MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Use strong key exchange
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521

# Log level
LogLevel VERBOSE

# Disable empty passwords
PermitEmptyPasswords no

# Disable .rhosts
IgnoreRhosts yes

# Strict mode
StrictModes yes
EOF
else
    # Modify main config
    log "Modifying main sshd_config..."

    # Backup and modify
    sed -i.bak \
        -e 's/^#*PermitRootLogin.*/PermitRootLogin prohibit-password/' \
        -e 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' \
        -e 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/' \
        -e 's/^#*MaxAuthTries.*/MaxAuthTries 3/' \
        -e 's/^#*X11Forwarding.*/X11Forwarding no/' \
        -e 's/^#*PermitEmptyPasswords.*/PermitEmptyPasswords no/' \
        -e 's/^#*LogLevel.*/LogLevel VERBOSE/' \
        "$SSHD_CONFIG"

    # Add settings if they don't exist
    grep -q "^AllowTcpForwarding" "$SSHD_CONFIG" || echo "AllowTcpForwarding no" >> "$SSHD_CONFIG"
    grep -q "^AllowAgentForwarding" "$SSHD_CONFIG" || echo "AllowAgentForwarding no" >> "$SSHD_CONFIG"
fi

log "SSH configuration updated"

# Test configuration
log "Testing SSH configuration..."
if sshd -t 2>&1; then
    log "SSH configuration is valid"
else
    log "ERROR: SSH configuration is invalid!"
    echo "Restoring backup..."
    cp "$BACKUP_DIR/sshd_config" "$SSHD_CONFIG" 2>/dev/null || true
    rm -f "$CUSTOM_CONFIG" 2>/dev/null || true
    exit 1
fi

# Restart SSH
echo ""
read -p "Restart SSH service now? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log "Restarting SSH service..."
    systemctl restart sshd || systemctl restart ssh

    if systemctl is-active --quiet sshd 2>/dev/null || systemctl is-active --quiet ssh 2>/dev/null; then
        log "SSH service restarted successfully"
    else
        log "ERROR: SSH service failed to start!"
        echo "Restoring backup..."
        cp "$BACKUP_DIR/sshd_config" "$SSHD_CONFIG" 2>/dev/null || true
        rm -f "$CUSTOM_CONFIG" 2>/dev/null || true
        systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null
        exit 1
    fi
else
    log "SSH restart skipped. Run 'systemctl restart sshd' when ready."
fi

echo ""
echo "============================================"
echo "SSH HARDENING COMPLETE"
echo "============================================"
echo ""
echo "Applied settings:"
echo "  - Root login: key-only (prohibit-password)"
echo "  - Password auth: enabled"
echo "  - Max auth tries: 3"
echo "  - X11/TCP forwarding: disabled"
echo "  - Logging: VERBOSE"
echo ""
echo "Backup location: $BACKUP_DIR"
echo ""
echo "VERIFICATION STEPS:"
echo "1. Keep this session open"
echo "2. Open a NEW terminal and test SSH login"
echo "3. If login fails, restore from backup:"
echo "   cp $BACKUP_DIR/ssh/sshd_config /etc/ssh/sshd_config"
echo "   systemctl restart sshd"
echo ""
log "SSH hardening complete"
