#!/bin/bash
###############################################################################
# 07-dovecot-harden.sh - Dovecot IMAP/POP3 Hardening
# Target: Linux Mail Server with Dovecot
# Purpose: Secure Dovecot configuration
###############################################################################

set -euo pipefail

LOGFILE="/root/ccdc-logs/dovecot_harden_$(date +%Y%m%d_%H%M%S).log"
BACKUP_DIR="/root/ccdc-backups/dovecot_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$(dirname "$LOGFILE")" "$BACKUP_DIR"

log() {
    echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOGFILE"
}

section() {
    echo "" | tee -a "$LOGFILE"
    echo "========================================" | tee -a "$LOGFILE"
    echo "=== $1" | tee -a "$LOGFILE"
    echo "========================================" | tee -a "$LOGFILE"
}

log "Starting Dovecot hardening..."

# Check if Dovecot is installed
if ! command -v doveconf &> /dev/null; then
    log "ERROR: Dovecot is not installed"
    exit 1
fi

# Backup current configuration
log "Backing up Dovecot configuration..."
cp -a /etc/dovecot "$BACKUP_DIR/"
doveconf -n > "$BACKUP_DIR/doveconf-n-before.txt"

section "CURRENT DOVECOT CONFIGURATION AUDIT"

echo "--- Version ---" | tee -a "$LOGFILE"
dovecot --version 2>/dev/null | tee -a "$LOGFILE"

echo "" | tee -a "$LOGFILE"
echo "--- Protocols ---" | tee -a "$LOGFILE"
doveconf protocols 2>/dev/null | tee -a "$LOGFILE"

echo "" | tee -a "$LOGFILE"
echo "--- SSL Configuration ---" | tee -a "$LOGFILE"
doveconf ssl 2>/dev/null | tee -a "$LOGFILE"
doveconf ssl_cert 2>/dev/null | tee -a "$LOGFILE"
doveconf ssl_key 2>/dev/null | tee -a "$LOGFILE"
doveconf ssl_min_protocol 2>/dev/null | tee -a "$LOGFILE" || echo "ssl_min_protocol not set" | tee -a "$LOGFILE"

echo "" | tee -a "$LOGFILE"
echo "--- Auth Configuration ---" | tee -a "$LOGFILE"
doveconf -n auth 2>/dev/null | head -30 | tee -a "$LOGFILE"

echo "" | tee -a "$LOGFILE"
echo "--- Login Process ---" | tee -a "$LOGFILE"
doveconf login_greeting 2>/dev/null | tee -a "$LOGFILE"
doveconf auth_verbose 2>/dev/null | tee -a "$LOGFILE"

echo ""
echo "============================================"
echo "DOVECOT HARDENING OPTIONS"
echo "============================================"
echo ""

read -p "Apply Dovecot security hardening? (y/N): " -r REPLY
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log "Aborted by user"
    exit 0
fi

# Find the main config file or local config
DOVECOT_CONF="/etc/dovecot/dovecot.conf"
DOVECOT_LOCAL="/etc/dovecot/local.conf"
CONF_D="/etc/dovecot/conf.d"

# Create a local config file for our changes
if [ -d "$CONF_D" ]; then
    HARDENING_CONF="$CONF_D/99-ccdc-hardening.conf"
else
    HARDENING_CONF="$DOVECOT_LOCAL"
fi

log "Creating hardening configuration at: $HARDENING_CONF"

section "APPLYING DOVECOT HARDENING"

# Start building the hardening config
cat > "$HARDENING_CONF" << 'EOF'
# CCDC Dovecot Hardening Configuration
# Generated by 07-dovecot-harden.sh

EOF

# 1. SSL/TLS Configuration
echo ""
echo "=== SSL/TLS Configuration ==="
CURRENT_SSL=$(doveconf -h ssl 2>/dev/null || echo "no")
echo "Current SSL setting: $CURRENT_SSL"

read -p "Require SSL/TLS for all connections? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat >> "$HARDENING_CONF" << 'EOF'
# Require SSL/TLS
ssl = required

EOF
    log "SSL set to required"
else
    cat >> "$HARDENING_CONF" << 'EOF'
# Enable SSL/TLS (not required)
ssl = yes

EOF
    log "SSL set to yes (optional)"
fi

# Check for SSL certificates
SSL_CERT=$(doveconf -h ssl_cert 2>/dev/null | sed 's/<//g' || echo "")
SSL_KEY=$(doveconf -h ssl_key 2>/dev/null | sed 's/<//g' || echo "")

if [ -z "$SSL_CERT" ] || [ ! -f "$SSL_CERT" ]; then
    echo ""
    echo "No SSL certificate configured."
    echo "Common locations:"
    echo "  /etc/ssl/certs/dovecot.pem"
    echo "  /etc/letsencrypt/live/domain/fullchain.pem"
    echo "  /etc/pki/dovecot/certs/dovecot.pem"
    read -p "Enter certificate path (or Enter to skip): " -r CERT_PATH
    if [ -n "$CERT_PATH" ] && [ -f "$CERT_PATH" ]; then
        read -p "Enter key path: " -r KEY_PATH
        if [ -n "$KEY_PATH" ] && [ -f "$KEY_PATH" ]; then
            cat >> "$HARDENING_CONF" << EOF
ssl_cert = <$CERT_PATH
ssl_key = <$KEY_PATH

EOF
            log "SSL certificate configured"
        fi
    fi
fi

# SSL Protocol settings
cat >> "$HARDENING_CONF" << 'EOF'
# Modern TLS only (disable SSLv3, TLSv1, TLSv1.1)
ssl_min_protocol = TLSv1.2

# Strong ciphers
ssl_cipher_list = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

# Prefer server cipher order
ssl_prefer_server_ciphers = yes

EOF
log "TLS protocol and cipher settings configured"

# 2. Authentication settings
echo ""
echo "=== Authentication Settings ==="

cat >> "$HARDENING_CONF" << 'EOF'
# Disable plaintext auth without SSL
disable_plaintext_auth = yes

# Authentication mechanisms (PLAIN and LOGIN require SSL)
auth_mechanisms = plain login

# Verbose auth logging (useful for troubleshooting)
auth_verbose = yes

# Log failed auth attempts
auth_verbose_passwords = no

# Authentication failure delay
auth_failure_delay = 2 secs

EOF
log "Authentication settings configured"

# 3. Login banner
echo ""
echo "=== Login Banner ==="
cat >> "$HARDENING_CONF" << 'EOF'
# Minimal login greeting (hide version)
login_greeting = Mail Server Ready

EOF
log "Login greeting simplified"

# 4. Connection limits
echo ""
echo "=== Connection Limits ==="
read -p "Configure connection limits? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat >> "$HARDENING_CONF" << 'EOF'
# Connection limits
mail_max_userip_connections = 20

# Process limits
default_process_limit = 100
default_client_limit = 1000

EOF
    log "Connection limits configured"
fi

# 5. Logging
echo ""
echo "=== Logging Configuration ==="
cat >> "$HARDENING_CONF" << 'EOF'
# Enhanced logging
log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot-info.log
debug_log_path = /var/log/dovecot-debug.log

# Log timestamp format
log_timestamp = "%Y-%m-%d %H:%M:%S "

# Login logging
login_log_format_elements = user=<%u> method=%m rip=%r lip=%l mpid=%e %c %k

EOF
log "Logging configuration set"

# 6. Protocol-specific settings
echo ""
echo "=== Protocol Settings ==="

CURRENT_PROTOCOLS=$(doveconf -h protocols 2>/dev/null || echo "imap pop3")
echo "Current protocols: $CURRENT_PROTOCOLS"

read -p "Disable POP3 (keep IMAP only)? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat >> "$HARDENING_CONF" << 'EOF'
# IMAP only (POP3 disabled)
protocols = imap lmtp

EOF
    log "POP3 disabled, IMAP only"
else
    cat >> "$HARDENING_CONF" << 'EOF'
# Enable IMAP and POP3
protocols = imap pop3 lmtp

EOF
    log "IMAP and POP3 enabled"
fi

# 7. LMTP/Postfix integration
echo ""
echo "=== Postfix Integration ==="
read -p "Configure SASL auth for Postfix? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cat >> "$HARDENING_CONF" << 'EOF'
# SASL auth for Postfix
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

EOF
    log "Postfix SASL auth configured"

    # Update Postfix to use Dovecot SASL
    if command -v postconf &> /dev/null; then
        echo ""
        read -p "Update Postfix to use Dovecot SASL? (y/N): " -r REPLY
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            postconf -e "smtpd_sasl_type = dovecot"
            postconf -e "smtpd_sasl_path = private/auth"
            postconf -e "smtpd_sasl_auth_enable = yes"
            postconf -e "smtpd_sasl_security_options = noanonymous"
            postconf -e "smtpd_sasl_local_domain = \$myhostname"
            log "Postfix SASL settings updated"
        fi
    fi
fi

# 8. Security-related settings
cat >> "$HARDENING_CONF" << 'EOF'
# Additional security
# Prevent username enumeration
auth_policy_check_before_auth = yes

# Drop privileges
first_valid_uid = 1000
last_valid_uid = 65534

EOF

# Verify configuration
section "VERIFYING CONFIGURATION"
log "Checking Dovecot configuration..."

if doveconf -n > /dev/null 2>&1; then
    log "Dovecot configuration is valid"
else
    log "WARNING: Configuration errors detected"
    doveconf -n 2>&1 | tail -20 | tee -a "$LOGFILE"
fi

# Show the new config
echo ""
echo "New hardening configuration:"
cat "$HARDENING_CONF"

# Restart Dovecot
echo ""
read -p "Restart Dovecot to apply changes? (y/N): " -r REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log "Restarting Dovecot..."
    systemctl restart dovecot
    if systemctl is-active --quiet dovecot; then
        log "Dovecot restarted successfully"
    else
        log "ERROR: Dovecot failed to restart!"
        echo "Check: journalctl -xe -u dovecot"
        echo "Restoring backup..."
        rm -f "$HARDENING_CONF"
        cp -a "$BACKUP_DIR/dovecot/"* /etc/dovecot/
        systemctl restart dovecot
        exit 1
    fi
else
    log "Restart skipped. Run 'systemctl restart dovecot' when ready."
fi

echo ""
echo "============================================"
echo "DOVECOT HARDENING COMPLETE"
echo "============================================"
echo ""
echo "Applied hardening:"
echo "  - SSL/TLS enforced (if certificates available)"
echo "  - Modern TLS protocols only (TLSv1.2+)"
echo "  - Strong cipher suites"
echo "  - Plaintext auth disabled without SSL"
echo "  - Login greeting simplified"
echo "  - Enhanced logging enabled"
echo "  - Auth failure delay configured"
echo ""
echo "Backup location: $BACKUP_DIR"
echo "Hardening config: $HARDENING_CONF"
echo ""
echo "VERIFICATION:"
echo "  1. Test IMAP connection:"
echo "     openssl s_client -connect localhost:993"
echo "  2. Test IMAP with STARTTLS:"
echo "     openssl s_client -connect localhost:143 -starttls imap"
echo "  3. Check logs:"
echo "     tail -f /var/log/dovecot.log"
echo "  4. Test authentication with mail client"
echo ""

log "Dovecot hardening complete"
